apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pythonweb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: pythonapp-svc
    servicePort: 5000
  rules:
  - host: myminikube.info
    http:
      paths:
      - path: /
        backend:
          serviceName: pythonapp-svc
          servicePort: 5000
